// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.UnicodeEscapeUnescape
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("action")]
        public string Action { get; set; }

        [JsonProperty("original")]
        public string Original { get; set; }

        [JsonProperty("escaped")]
        public string Escaped { get; set; }

        [JsonProperty("character_count")]
        public long CharacterCount { get; set; }

        [JsonProperty("unicode_points")]
        public UnicodePoint[] UnicodePoints { get; set; }
    }

    public partial class UnicodePoint
    {
        [JsonProperty("char")]
        public string Char { get; set; }

        [JsonProperty("unicode")]
        public string Unicode { get; set; }

        [JsonProperty("codepoint")]
        public string Codepoint { get; set; }
    }
}
